/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_Database */

#ifndef _Included_application_Database
#define _Included_application_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_Database
 * Method:    createDatabase
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_Database_createDatabase
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    getTableNames
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Database_getTableNames
  (JNIEnv *, jobject);

/*
 * Class:     application_Database
 * Method:    executeQuery
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_application_Database_executeQuery
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    importCustomFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_Database_importCustomFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    exportCustomFormat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_Database_exportCustomFormat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     application_Database
 * Method:    exportSQL
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_application_Database_exportSQL
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
